#!/bin/bash
# Railway one-click deployment helper
# This script helps you deploy to Railway

echo "🚀 Railway Deployment Helper"
echo "=============================="
echo ""
echo "To deploy to Railway:"
echo ""
echo "1. Go to: https://railway.app"
echo "2. Sign in with GitHub"
echo "3. Click 'Create New Project'"
echo "4. Click 'Provision PostgreSQL'"
echo "5. Click 'New' → 'From GitHub Repo'"
echo "6. Select: kryptbakar/polished-prompt"
echo "7. Click 'Deploy Now'"
echo ""
echo "While deploying, set these environment variables:"
echo ""
echo "📋 COPY AND PASTE THESE:"
echo "DATABASE_URL=postgresql://postgres:password@localhost:5432/railway"
echo "SESSION_SECRET=super-secret-key-production-2025-randomstring"
echo "NODE_ENV=production"
echo "PORT=5000"
echo "REPL_ID=railway-prod"
echo ""
echo "Get DATABASE_URL from:"
echo "- PostgreSQL service → Variables tab → Copy DATABASE_URL"
echo ""
echo "✅ Once deployed, copy your Railway URL"
echo "Example: https://polished-prompt-prod.up.railway.app"
echo ""
echo "You'll need this for Vercel deployment!"
